[project]
name = "receipt-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thrinaibatchu", email = "172543756+thrinaibatchu@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
receipt-project = "receipt_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
