import os

import psycopg
from dotenv import load_dotenv


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name TEXT NOT NULL,
    purchase_date DATE,
    subtotal NUMERIC(12, 2),
    tax NUMERIC(12, 2),
    total NUMERIC(12, 2) NOT NULL,
    transaction_id TEXT,
    source_file TEXT NOT NULL,
    source_hash TEXT UNIQUE,
    receipt_fingerprint TEXT UNIQUE,
    source_type TEXT NOT NULL DEFAULT 'live_receipt',
    warehouse_number TEXT,
    register_number TEXT,
    historical_transaction_number TEXT,
    transaction_time TEXT,
    historical_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS
    receipts_historical_key_uidx
ON receipts (historical_key)
WHERE historical_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    category TEXT
);

CREATE TABLE IF NOT EXISTS receipt_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL,
    product_id BIGINT,
    store_item_code TEXT,
    raw_description TEXT NOT NULL,
    quantity NUMERIC(12, 3) NOT NULL DEFAULT 1,
    unit_price NUMERIC(12, 2),
    total_price NUMERIC(12, 2) NOT NULL,
    source_row_number INTEGER,
    historical_row_type TEXT,
    FOREIGN KEY (receipt_id) REFERENCES receipts(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS receipt_discounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL,
    raw_description TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    related_item_code TEXT,
    source_row_number INTEGER,
    historical_row_type TEXT,
    FOREIGN KEY (receipt_id) REFERENCES receipts(id)
);
"""


def create_database() -> None:
    load_dotenv()

    database_url = os.getenv(
        "DATABASE_URL"
    )

    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is missing"
        )

    with psycopg.connect(
        database_url
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                SCHEMA_SQL
            )

        connection.commit()

    print(
        "Neon V2 receipt schema created "
        "successfully"
    )


if __name__ == "__main__":
    create_database()
